async function admin(){
  const sessionToken=sessionStorage.getItem('teacherSession')||'';
  if(!sessionToken){location.href=location.pathname;return}
  app.innerHTML='<main class="admin"><header>'+brand()+'<button class="ghost" onclick="logoutTeacher()">登出</button></header><div class="admin-main"><div class="admin-nav"><button id="navRoom" class="active" onclick="showAdminTab(\'room\')">建立搶答房間</button><button id="navBank" onclick="showAdminTab(\'bank\')">題庫管理</button></div><section id="roomTab" class="panel"><h2>建立搶答房間</h2><p>登入驗證完成，輸入活動名稱即可建立房間。</p><label class="field">活動名稱<input id="adminRoomTitle" value="今天的課堂挑戰" maxlength="50"></label><button class="primary" onclick="createAdminRoom()">建立房間 →</button><p id="adminRoomErr"></p></section><section id="bankTab" class="hidden"><div class="admin-grid"><div class="panel"><h2 id="formTitle">新增題目</h2><label class="field">題型<select id="qType" onchange="toggleOptions()"><option value="single">單選題</option><option value="truefalse">是非題</option><option value="short">簡答題</option></select></label><div class="form-row"><label class="field">分類<input id="qCategory" placeholder="例如：國語"></label><label class="field">適用年級<input id="qGrade" placeholder="例如：三年級"></label></div><label class="field">題目<textarea id="qQuestion" placeholder="請輸入題目內容"></textarea></label><div id="optionFields"><div class="form-row"><label class="field">選項 A<input id="qA"></label><label class="field">選項 B<input id="qB"></label></div><div class="form-row"><label class="field">選項 C<input id="qC"></label><label class="field">選項 D<input id="qD"></label></div></div><label class="field">正確答案<input id="qAnswer" placeholder="單選題請填 A、B、C 或 D"></label><label class="field">答案解析<textarea id="qExplanation" placeholder="選填"></textarea></label><div class="form-row"><label class="field">配分<input id="qScore" type="number" min="1" max="100" value="1"></label><label class="field">狀態<select id="qEnabled"><option value="true">啟用</option><option value="false">停用</option></select></label></div><div class="question-actions"><button class="primary" onclick="saveQuestion()">儲存題目</button><button class="secondary" onclick="clearQuestionForm()">清除</button></div><p id="qErr"></p></div><div class="panel"><h2>題庫列表</h2><div class="toolbar"><input id="qKeyword" placeholder="搜尋題目、分類或年級" oninput="filterQuestions()"><select id="qFilterType" onchange="filterQuestions()"><option value="">全部題型</option><option value="single">單選題</option><option value="truefalse">是非題</option><option value="short">簡答題</option></select><button class="ghost" onclick="loadQuestions()">重新整理</button></div><div id="qList" class="q-list"><div class="empty">正在讀取題庫…</div></div></div></div></section></div></main>';
  await loadQuestions();
}
function logoutTeacher(){sessionStorage.removeItem('teacherSession');location.href=location.pathname}
function showAdminTab(tab){roomTab.classList.toggle('hidden',tab!=='room');bankTab.classList.toggle('hidden',tab!=='bank');navRoom.classList.toggle('active',tab==='room');navBank.classList.toggle('active',tab==='bank')}
async function createAdminRoom(){adminRoomErr.textContent='';try{const d=await api({action:'create',title:adminRoomTitle.value,sessionToken:sessionStorage.getItem('teacherSession')});localStorage.setItem('teacher:'+d.code,d.teacherToken);location.href='?mode=teacher&code='+d.code}catch(e){adminRoomErr.className='error';adminRoomErr.textContent=e.message}}
function toggleOptions(){optionFields.classList.toggle('hidden',qType.value!=='single');qAnswer.placeholder=qType.value==='single'?'請填 A、B、C 或 D':qType.value==='truefalse'?'請填 true 或 false':'請輸入參考答案'}
async function loadQuestions(){try{const d=await api({action:'listQuestions',sessionToken:sessionStorage.getItem('teacherSession')});state.questions=d.questions;filterQuestions()}catch(e){qList.innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
function filterQuestions(){
  const k=(qKeyword.value||'').toLowerCase(),t=qFilterType.value,labels={single:'單選題',truefalse:'是非題',short:'簡答題'};
  const list=state.questions.filter(q=>(!t||q.type===t)&&(!k||(q.question+' '+q.category+' '+q.grade).toLowerCase().includes(k)));
  qList.innerHTML=list.length?list.map(q=>'<article class="q-item"><div><span class="badge '+(q.enabled?'':'off')+'">'+labels[q.type]+' · '+(q.enabled?'啟用':'停用')+'</span><small> '+esc(q.category||'未分類')+'｜'+esc(q.grade||'全年級')+'｜'+q.score+' 分</small><h3>'+esc(q.question)+'</h3><div class="answer">答案：'+esc(q.answer)+'</div></div><div><button onclick="editQuestion(\''+q.id+'\')">編輯</button> <button onclick="removeQuestion(\''+q.id+'\')">刪除</button></div></article>').join(''):'<div class="empty">目前沒有符合條件的題目</div>';
}
function clearQuestionForm(){state.editing=null;formTitle.textContent='新增題目';qType.value='single';qCategory.value=qGrade.value=qQuestion.value=qA.value=qB.value=qC.value=qD.value=qAnswer.value=qExplanation.value='';qScore.value=1;qEnabled.value='true';qErr.textContent='';toggleOptions()}
function editQuestion(id){const q=state.questions.find(x=>x.id===id);if(!q)return;state.editing=id;formTitle.textContent='編輯題目';qType.value=q.type;qCategory.value=q.category||'';qGrade.value=q.grade||'';qQuestion.value=q.question||'';qA.value=q.optionA||'';qB.value=q.optionB||'';qC.value=q.optionC||'';qD.value=q.optionD||'';qAnswer.value=q.answer||'';qExplanation.value=q.explanation||'';qScore.value=q.score||1;qEnabled.value=String(q.enabled);toggleOptions();window.scrollTo({top:0,behavior:'smooth'})}
async function saveQuestion(){
  qErr.textContent='';
  const data={id:state.editing,type:qType.value,category:qCategory.value,grade:qGrade.value,question:qQuestion.value,optionA:qA.value,optionB:qB.value,optionC:qC.value,optionD:qD.value,answer:qAnswer.value,explanation:qExplanation.value,score:Number(qScore.value)||1,enabled:qEnabled.value==='true'};
  try{await api({action:'saveQuestion',sessionToken:sessionStorage.getItem('teacherSession'),questionData:data});clearQuestionForm();await loadQuestions();alert('題目已儲存')}catch(e){qErr.className='error';qErr.textContent=e.message}
}
async function removeQuestion(id){if(!confirm('確定刪除這一題？'))return;try{await api({action:'deleteQuestion',sessionToken:sessionStorage.getItem('teacherSession'),questionId:id});await loadQuestions()}catch(e){alert(e.message)}}
